# Generated by Django 6.1.1 on 2026-09-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('issue_type', models.CharField(choices=[('OVERFLOWING_BIN', 'Overflowing Bin'), ('GARBAGE_ON_ROAD', 'Garbage on Road'), ('ILLEGAL_DUMPING', 'Illegal Dumping'), ('MISSED_COLLECTION', 'Missed Collection'), ('IMPROPER_SEGREGATION', 'Improper Waste Segregation'), ('OTHER', 'Other Waste Issue')], max_length=40)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('location', models.CharField(help_text='Location or area name, e.g., North Gate, Main Road', max_length=255)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark to assist sanitation crew', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/%Y/%m/')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('assigned_crew', models.CharField(blank=True, default='', help_text='Crew name or vehicle assigned', max_length=120)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Notes from municipality dispatch team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_updates', to='waste_management.complaint')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('waste_category', models.CharField(choices=[('ORGANIC', 'Organic / Wet Waste'), ('PLASTIC', 'Plastic (Bottles, Containers, Wrappers)'), ('PAPER', 'Paper & Cardboard'), ('E_WASTE', 'E-Waste (Electronics, Batteries, Gadgets)'), ('GLASS', 'Glass (Bottles, Jars, Broken Glass)'), ('METAL', 'Metal & Scrap Materials'), ('GENERAL', 'General Solid Waste'), ('OTHER', 'Other Miscellaneous Waste')], max_length=30)),
                ('quantity', models.CharField(help_text='e.g. 2 bags, 1 carton box, ~10 kg', max_length=100)),
                ('pickup_address', models.TextField(help_text='Complete address with flat/door number')),
                ('preferred_date', models.DateField(help_text='Preferred collection date')),
                ('preferred_time', models.CharField(default='Morning (09:00 AM - 12:00 PM)', help_text='Time window for pickup', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Access instructions, gate codes, or special handling')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=20)),
                ('assigned_vehicle', models.CharField(blank=True, default='', help_text='Vehicle or team assigned', max_length=100)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Contact number for SMS/call verification', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Default residence or society address', max_length=255)),
                ('is_admin_staff', models.BooleanField(default=False, help_text='Designates if this citizen is an admin staff member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
