# Generated by Django 5.2.17 on 2026-09-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Street address or location name', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(default=28.6139, help_text='GPS Latitude coordinate'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(default=77.209, help_text='GPS Longitude coordinate'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='latitude',
            field=models.FloatField(default=28.6139, help_text='GPS Latitude coordinate'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='longitude',
            field=models.FloatField(default=77.209, help_text='GPS Longitude coordinate'),
        ),
    ]
