# Generated by Django 5.2.17 on 2026-09-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_complaint_address_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clean_coins',
            field=models.IntegerField(default=100, help_text='CleanCoins reward balance earned through verified reports'),
        ),
    ]
