# Generated by Django 4.2.30 on 2026-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0003_userprofile_clean_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug', max_length=255, null=True, unique=True),
        ),
    ]
