# Generated by Django 4.2.30 on 2026-09-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0004_complaint_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='slug',
        ),
    ]
