document.addEventListener('DOMContentLoaded', function() {
    const mapContainers = document.querySelectorAll('.folium-map-container');
    
    if (mapContainers.length === 0) return;

    mapContainers.forEach(container => {
        const isReadOnly = container.hasAttribute('data-readonly');
        const latInput = document.getElementById('id_latitude');
        const lngInput = document.getElementById('id_longitude');
        const geoBtn = document.getElementById('btn-geolocate');
        
        // Find the iframe generated by leafmap/folium
        const iframe = container.querySelector('iframe');
        if (!iframe) return;

        iframe.style.width = '100%';
        iframe.style.height = '100%';
        iframe.style.border = 'none';
        iframe.style.borderRadius = '8px';

        iframe.onload = function() {
            const iframeWin = iframe.contentWindow;
            let mapObj = null;
            let L = iframeWin.L;

            // Folium assigns map variables starting with map_
            for (let key in iframeWin) {
                if (key.startsWith('map_')) {
                    mapObj = iframeWin[key];
                    break;
                }
            }

            if (!mapObj || !L) return;

            let marker = null;

            // Initialize marker from hidden inputs if they exist (form re-render)
            if (!isReadOnly && latInput && lngInput && latInput.value && lngInput.value) {
                const savedLat = parseFloat(latInput.value);
                const savedLng = parseFloat(lngInput.value);
                if (!isNaN(savedLat) && !isNaN(savedLng)) {
                    marker = L.marker([savedLat, savedLng]).addTo(mapObj);
                    mapObj.setView([savedLat, savedLng], 15);
                }
            }

            if (!isReadOnly) {
                // Click to place marker
                mapObj.on('click', function(e) {
                    const lat = e.latlng.lat;
                    const lng = e.latlng.lng;

                    if (marker) {
                        marker.setLatLng(e.latlng);
                    } else {
                        marker = L.marker(e.latlng).addTo(mapObj);
                    }

                    if (latInput && lngInput) {
                        latInput.value = lat.toFixed(6);
                        lngInput.value = lng.toFixed(6);
                    }
                });

                // Geolocation button
                if (geoBtn) {
                    geoBtn.addEventListener('click', function() {
                        if ("geolocation" in navigator) {
                            geoBtn.textContent = "📍 Locating...";
                            navigator.geolocation.getCurrentPosition(function(position) {
                                const lat = position.coords.latitude;
                                const lng = position.coords.longitude;
                                
                                const newLatLng = new L.LatLng(lat, lng);
                                mapObj.setView(newLatLng, 15);
                                
                                if (marker) {
                                    marker.setLatLng(newLatLng);
                                } else {
                                    marker = L.marker(newLatLng).addTo(mapObj);
                                }

                                if (latInput && lngInput) {
                                    latInput.value = lat.toFixed(6);
                                    lngInput.value = lng.toFixed(6);
                                }
                                geoBtn.textContent = "📍 Use My Current Location";
                            }, function(error) {
                                alert("Could not get your location. Please check browser permissions.");
                                geoBtn.textContent = "📍 Use My Current Location";
                            });
                        } else {
                            alert("Geolocation is not supported by your browser");
                        }
                    });
                }
            }
        };
    });
});
